# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 527)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.closeButton = QtWidgets.QPushButton(self.centralwidget)
        self.closeButton.setGeometry(QtCore.QRect(700, 20, 81, 31))
        self.closeButton.setObjectName("closeButton")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(680, 80, 111, 361))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(10, 0, 0, 0)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cameraButton = QtWidgets.QPushButton(self.layoutWidget)
        self.cameraButton.setMinimumSize(QtCore.QSize(50, 35))
        self.cameraButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.cameraButton.setObjectName("cameraButton")
        self.verticalLayout.addWidget(self.cameraButton)
        self.discheckBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.discheckBox.setChecked(True)
        self.discheckBox.setTristate(False)
        self.discheckBox.setObjectName("discheckBox")
        self.verticalLayout.addWidget(self.discheckBox)
        self.facecheckBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.facecheckBox.setTristate(False)
        self.facecheckBox.setObjectName("facecheckBox")
        self.verticalLayout.addWidget(self.facecheckBox)
        self.handscheckBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.handscheckBox.setTristate(False)
        self.handscheckBox.setObjectName("handscheckBox")
        self.verticalLayout.addWidget(self.handscheckBox)
        self.posecheckBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.posecheckBox.setTristate(False)
        self.posecheckBox.setObjectName("posecheckBox")
        self.verticalLayout.addWidget(self.posecheckBox)
        self.volumecheckBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.volumecheckBox.setTristate(False)
        self.volumecheckBox.setObjectName("volumecheckBox")
        self.verticalLayout.addWidget(self.volumecheckBox)
        self.fpscheckBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.fpscheckBox.setTristate(False)
        self.fpscheckBox.setObjectName("fpscheckBox")
        self.verticalLayout.addWidget(self.fpscheckBox)
        self.handcontroncheckBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.handcontroncheckBox.setTristate(False)
        self.handcontroncheckBox.setObjectName("handcontroncheckBox")
        self.verticalLayout.addWidget(self.handcontroncheckBox)
        self.imglabel = QtWidgets.QLabel(self.centralwidget)
        self.imglabel.setGeometry(QtCore.QRect(20, 20, 640, 480))
        self.imglabel.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius : 30px")
        self.imglabel.setText("")
        self.imglabel.setObjectName("imglabel")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.closeButton.clicked.connect(MainWindow.colseprogram)
        self.cameraButton.clicked.connect(MainWindow.controlcamera)
        self.discheckBox.clicked['bool'].connect(MainWindow.setdis)
        self.facecheckBox.clicked.connect(MainWindow.disface)
        self.handscheckBox.clicked.connect(MainWindow.dishand)
        self.posecheckBox.clicked.connect(MainWindow.dispose)
        self.volumecheckBox.clicked.connect(MainWindow.controlvalue)
        self.fpscheckBox.clicked.connect(MainWindow.disfps)
        self.handcontroncheckBox.clicked.connect(MainWindow.VirtualMouseControl_Clicked)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.closeButton.setText(_translate("MainWindow", "关闭"))
        self.cameraButton.setText(_translate("MainWindow", "打开摄像头"))
        self.discheckBox.setText(_translate("MainWindow", "显示"))
        self.facecheckBox.setText(_translate("MainWindow", "脸部识别"))
        self.handscheckBox.setText(_translate("MainWindow", "手部识别"))
        self.posecheckBox.setText(_translate("MainWindow", "肢体识别"))
        self.volumecheckBox.setText(_translate("MainWindow", "音量控制"))
        self.fpscheckBox.setText(_translate("MainWindow", "显示帧率"))
        self.handcontroncheckBox.setText(_translate("MainWindow", "手势控制鼠标"))
